apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1GQ0dfQ2F0YWxvZztVc2VyIElkPXNhO1Bhc3N3b3JkPUZDR0BQYXNzd29yZDEyMztUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU=
  jwt-secret-key: ZmNnLXNlY3JldC1rZXktMjAyNC1zdXBlci1zZWd1cmEtMjU2Yml0cw==
