apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1GQ0dfUGF5bWVudHM7VXNlciBJZD1zYTtQYXNzd29yZD1GQ0dAUGFzc3dvcmQxMjM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl
