apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RABBITMQ_HOST: "rabbitmq"
  Jwt__Issuer: "FCG.UsersAPI"
  Jwt__Audience: "FCG.Client"
  Jwt__ExpiracaoHoras: "8"
