apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1GQ0dfVXNlcnM7VXNlciBJZD1zYTtQYXNzd29yZD1GQ0dAUGFzc3dvcmQxMjM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl
  jwt-secret-key: ZmNnLXNlY3JldC1rZXktMjAyNC1zdXBlci1zZWd1cmEtMjU2Yml0cw==
